name: Changed Directories
description: Detects changed directories in a push or pull request events
branding:
  icon: folder
  color: blue
runs:
  using: 'node12'
  main:  'dist/index.js'
inputs:
  baseDirectories:
    description: Space-delimited base directories.
    required: true
  token:
    description: GitHub token for authenticating GitHub API requests.
    required: true
outputs:
  directories:
    description: Space-delimited string of changed directories
