name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: 12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          npm run package

      - uses: EndBug/add-and-commit@v5.1.1
        with:
          add: 'dist'
          author_name: bot
          author_email: bot@bot
          message: regenerate dist file
