name: t

on:
  workflow_dispatch

jobs:
  j:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: 72cedbb007de41d852c379173e18ea7ef0ee7674
          base: main
          branch: test
          title: title
          body: body
