name: test

on:
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        body: bodyyyy
        title: titleee
        branch: test
        base: main
